source "http://rubygems.org"

gemspec

gem 'wagons', :path => '../../'

# Include the wagons you want attached in Wagonfile. 
# Do not check Wagonfile into source control.
#
# To create a Wagonfile suitable for development, run 'rake wagon:file'
#
wagonfile = File.expand_path('../Wagonfile', __FILE__)
eval(File.read(wagonfile)) if File.exist?(wagonfile)
