source "https://rubygems.org"

gem 'rails', ENV['RAILS_VERSION']

gem 'wagons', :path => File.expand_path(__FILE__).split("test#{File::SEPARATOR}dummy").first

group :development, :test do
  gem 'sqlite3'
end

group :test do
  gem 'mocha', :require => false
end

# Include the wagons you want attached in Wagonfile.
# Do not check Wagonfile into source control.
#
# To create a Wagonfile suitable for development, run 'rake wagon:file'
#
wagonfile = File.expand_path('../Wagonfile', __FILE__)
eval(File.read(wagonfile)) if File.exist?(wagonfile)
