name: Build

on:
  push:
  pull_request:
    branches: [$default-branch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1", "3.2"]
        gemfile:
          - Gemfile
          - test/ci/rails71.gemfile
        exclude:
          # Exclude Ruby 3.0 since it isn't supported with rails 7.2
          - ruby-version: "3.1"
            gemfile: Gemfile

    env:
      ROOT_BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rake
