name: Build

on:
  push:
  pull_request:
    branches: [$default-branch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1"]
        gemfile:
          - Gemfile
          - test/ci/rails52.gemfile
          - test/ci/rails60.gemfile
          - test/ci/rails61.gemfile
        exclude:
          - ruby-version: "3.0"
            gemfile: test/ci/rails52.gemfile
          - ruby-version: "3.1"
            gemfile: test/ci/rails52.gemfile
          # YAML loading issue only fixed in 6.1
          - ruby-version: "3.1"
            gemfile: test/ci/rails60.gemfile
    env:
      ROOT_BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rake
